### PR TITLE
Push to new registry

### PR DESCRIPTION
**Pull request by chribsen**

### CODE REVIEW

**Review by mex — COMMENTED** [review]
Why is this not using the head of master? Looks like a similar change was already made.

**Comment by mex** [comment]
And just a note, this is a public repo so stay aware of what information you include in the build steps.

**Review by mex — COMMENTED** [review]
Why is it no longer necessary to push to the old registry?

**Comment by chribsen** [comment]
I was just planning to change all the references soon as the image is only used in build steps

**Review by mex — APPROVED** [review]

**Pull request merged**
